{% set name = "google-cloud-dataproc" %}
{% set version = "1.0.0" %}
{% set sha256 = "42a6a736fcb28e35119ec21f22b268538ba2285dbe109cef147aa8dcd7eacd3d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python
    - google-api-core-grpc >=1.14.0,<2.0.0dev

test:
  imports:
    - grpc
    - google.cloud.dataproc
    - google.cloud.dataproc_v1

about:
  home: https://github.com/googleapis/python-dataproc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Dataproc API client library
  description: "Google Cloud Dataproc API client library manages Hadoop-based clusters and jobs on Google Cloud Platform. With Dataproc, enterprises get a fully managed, purpose-built cluster that can autoscale to support any data or analytics processing job.\nSee the [quick start guide](https://googleapis.dev/python/dataproc/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dataproc/latest/index.html
  dev_url: https://github.com/googleapis/python-dataproc

extra:
  recipe-maintainers:
    - parthea
